 @host = http://localhost:8000
 @endpoint = products
 @route = {{host}}/{{endpoint}}
 @productId = {{createProduct.response.body.id}}

 ###

// @name createProduct
POST {{route}} HTTP/1.1
Content-Type: application/json

{
    "name": "New product",
    "price": 100
}

###

// @name findProductById
GET {{route}}/{{productId}} HTTP/1.1
Content-Type: application/json

###

// @name updateProductById
PUT {{route}}/{{productId}} HTTP/1.1
Content-Type: application/json

{
    "name": "Updated product",
    "price": 200
}

###

// @name deleteProductById
DELETE {{route}}/hjkhjk HTTP/1.1
Content-Type: application/json